content/urls.py
from django.urls import path

from content import views

urlpatterns = [
    path('', views.index, name='index'),
]

finalproject2/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from home import views
from order import views as orderviews

urlpatterns = [

    path('', include('home.urls')),
    path('home/', include('home.urls')),
    path('product/', include('product.urls')),
    path('user/', include('user.urls')),
    path('order/', include('order.urls')),
    path('content/', include('content.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('admin/', admin.site.urls),

    path('aboutus/', views.aboutus, name='aboutus'),
    path('references/', views.references, name='references'),
    path('contact/', views.contact, name='contact'),
    path('category/<int:id>/<slug:slug>/', views.category_products, name='category_products'),
    path('product/<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    path('product/<int:id>/<slug:slug>/product_comment', views.product_comment, name='product_comment'),
    path('content/<int:id>/<slug:slug>/', views.contentdetail, name='contentdetail'),
    path('menu/<int:id>/', views.menu, name='menu'),
    path('search/', views.product_search, name='product_search'),
    path('search_auto/', views.product_search_auto, name='product_search_auto'),
    path('logout/', views.logout_view, name='logout_view'),
    path('login/', views.login_view, name='login_view'),
    path('signup/', views.signup_view, name='signup_view'),
    path('shopcart/', orderviews.shopcart, name='shopcart'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('addcomment/<int:id>', views.addcomment, name='addcomment'),
]

user/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('update/', views.user_update, name='user_update'),
    path('password/', views.change_password, name='change_password'),
    path('orders/', views.orders, name='orders'),
    path('orderdetail/<int:id>', views.orderdetail, name='orderdetail'),
    path('comments/', views.comments, name='comments'),
    path('deletecomment/<int:id>', views.deletecomment, name='deletecomment'),
]

content/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models

# Create your models here.
from django.urls import reverse
from django.utils.safestring import mark_safe
from mptt.models import MPTTModel
from mptt.fields import TreeForeignKey


class Menu(MPTTModel):
    STATUS = (
        ('True', 'Evet'),
        ('False', 'Hayır'),
    )
    parent = TreeForeignKey('self', blank=True, null=True, related_name='children', on_delete=models.CASCADE)
    title = models.CharField(max_length=100, unique=True)
    link = models.CharField(max_length=100, blank=True)
    status = models.CharField(max_length=10, choices=STATUS)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class MPTTMeta:
        order_insertion_by = ['title']

    def __str__(self):
        full_path = [self.title]
        k = self.parent
        while k is not None:
            full_path.append(k.title)
            k = k.parent
        return ' / '.join(full_path[::-1])


class Content(models.Model):
    TYPE = (
        ('menu', 'menu'),
        ('haber', 'haber'),
        ('duyuru', 'duyuru'),
        ('etkinlik', 'etkinlik'),
    )
    STATUS = (
        ('True', 'Evet'),
        ('False', 'Hayır'),
    )
    menu = models.OneToOneField(Menu, null=True, blank=True, on_delete=models.CASCADE)
    type = models.CharField(max_length=10, choices=TYPE)
    title = models.CharField(max_length=150)
    keywords = models.CharField(blank=True, max_length=255)
    description = models.CharField(blank=True, max_length=255)
    image = models.ImageField(blank=True, null=True, upload_to='images/')
    detail = RichTextUploadingField()
    slug = models.SlugField(null=False, unique=True)
    status = models.CharField(max_length=10, choices=STATUS)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def image_tag(self):
        return mark_safe('<img src="{}" height="50"/>'.format(self.image.url))

    image_tag.short_description = 'Image'

    def get_absolute_url(self):
        return reverse('content_detail', kwargs={'slug': self.slug})


class CImages(models.Model):
    content = models.ForeignKey(Content, on_delete=models.CASCADE)
    title = models.CharField(max_length=50, blank=True)
    image = models.ImageField(blank=True, upload_to='images/')

    def __str__(self):
        return self.title

    def image_tag(self):
        return mark_safe('<img src="{}" height="50"/>'.format(self.image.url))

    image_tag.short_description = 'Image'

home/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.forms import ModelForm, TextInput
from django.utils.safestring import mark_safe


class Setting(models.Model):
    STATUS = (
        ('True', 'Evet'),
        ('False', 'Hayır'),
    )
    title = models.CharField(max_length=30)
    keywords = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    company = models.CharField(max_length=50)
    address = models.CharField(blank=True, max_length=100)
    phone = models.CharField(blank=True, max_length=15)
    fax = models.CharField(blank=True, max_length=15)
    email = models.CharField(blank=True, max_length=50)
    smtpserver = models.CharField(blank=True, max_length=20)
    smtpemail = models.CharField(blank=True, max_length=20)
    smtppassword = models.CharField(blank=True, max_length=10)
    smtpport = models.CharField(blank=True, max_length=5)
    icon = models.ImageField(blank=True, upload_to='images/')
    facebook = models.CharField(blank=True, max_length=50)
    instagram = models.CharField(blank=True, max_length=50)
    twitter = models.CharField(blank=True, max_length=50)
    aboutus = RichTextUploadingField(blank=True)
    references = RichTextUploadingField(blank=True)
    contact = RichTextUploadingField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS)

    def __str__(self):
        return self.title


class ContactFormMessage(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Read', 'Read'),
        ('Closed', 'Closed'),

    )
    name = models.CharField(blank=True, max_length=30)
    email = models.CharField(blank=True, max_length=50)
    subject = models.CharField(blank=True, max_length=50)
    message = models.CharField(blank=True, max_length=255)
    status = models.CharField(max_length=10, choices=STATUS, default='New')
    ip = models.CharField(blank=True, max_length=30)
    note = models.CharField(blank=True, max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class ContactForm(ModelForm):
    class Meta:
        model = ContactFormMessage
        fields = ['name', 'email', 'subject', 'message']
        widgets = {
            'name': TextInput(attrs={'class': 'input', 'placeholder': 'Name and Surname'}),
            'subject': TextInput(attrs={'class': 'input', 'placeholder': 'Subject'}),
            'email': TextInput(attrs={'class': 'input', 'placeholder': 'Email Address'}),
            'message': TextInput(attrs={'class': 'input', 'placeholder': 'Your Message'}),
        }


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.CharField(blank=True, max_length=20)
    address = models.CharField(blank=True, max_length=150)
    city = models.CharField(blank=True, max_length=20)
    image = models.ImageField(blank=True, upload_to='images/users/')

    def __str__(self):
        return self.user.username

    def user_name(self):
        return self.user.first_name + ' ' + self.user.last_name + ' [' + self.user.username + '] '

    def image_tag(self):
        return mark_safe('<img src="{}" height="50"/>'.format(self.image.url))

    image_tag.short_description = 'Image'


class UserProfileForm(ModelForm):
    class Meta:
        model = UserProfile
        fields = ['phone', 'address', 'city', 'image']

product/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models

# Create your models here.
from django.forms import ModelForm
from django.urls import reverse
from django.utils.safestring import mark_safe
from mptt.fields import TreeForeignKey
from mptt.models import MPTTModel
from django.contrib.auth.models import User


class Category(MPTTModel):
    STATUS = (
        ('True', 'Evet'),
        ('False', 'Hayır'),
    )
    title = models.CharField(max_length=30)
    keywords = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    image = models.ImageField(blank=True, upload_to='images/')
    status = models.CharField(max_length=10, choices=STATUS)
    slug = models.SlugField(null=False, unique=True)
    parent = TreeForeignKey('self', blank=True, null=True, related_name='children', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class MPTTMeta:
        order_insertion_by = ['title']

    def __str__(self):
        full_path = [self.title]
        k = self.parent
        while k is not None:
            full_path.append(k.title)
            k = k.parent
        return ' / '.join(full_path[::-1])

    def image_tag(self):
        return mark_safe('<img src="{}" height="50"/>'.format(self.image.url))

    image_tag.short_description = 'Image'

    def get_absulute_url(self):
        return reverse('category_detail', kwargs={'slug': self.slug})


class Product(models.Model):
    STATUS = (
        ('True', 'Evet'),
        ('False', 'Hayır'),
    )
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=75)
    keywords = models.CharField(max_length=255)
    writer = models.CharField(max_length=75)
    publisher = models.CharField(max_length=75)
    image = models.ImageField(blank=True, upload_to='images/')
    price = models.FloatField()
    amount = models.IntegerField()
    detail = RichTextUploadingField()
    slug = models.SlugField(null=False, unique=True)
    status = models.CharField(max_length=10, choices=STATUS)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def get_cat_list(self):
        k = self.category
        breadcrumb = ["dummy"]
        while k is not None:
            breadcrumb.append(k.slug)
            k = k.parent

    def get_absulute_url(self):
        return reverse('product_detail', kwargs={'slug': self.slug})

    def image_tag(self):
        return mark_safe('<img src="{}" height="50"/>'.format(self.image.url))

    image_tag.short_description = 'Image'


class Images(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    title = models.CharField(max_length=75, blank=True)
    image = models.ImageField(blank=True, upload_to='images/')

    def __str__(self):
        return self.title

    def image_tag(self):
        return mark_safe('<img src="{}" height="50"/>'.format(self.image.url))

    image_tag.short_description = 'Image'


class Comment(models.Model):
    STATUS = (
        ('New', 'Yeni'),
        ('True', 'Evet'),
        ('False', 'Hayır'),
    )
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    subject = models.CharField(max_length=50)
    comment = models.CharField(max_length=200, blank=True)
    rate = models.IntegerField(blank=True)
    status = models.CharField(max_length=10, choices=STATUS, default='New')
    ip = models.CharField(blank=True, max_length=20)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.subject


class CommentFrom(ModelForm):
    class Meta:
        model = Comment
        fields = ['subject', 'comment', 'rate']

home/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SearchForm(forms.Form):
    query = forms.CharField(label='Search', max_length=100)


class SignUpForm(UserCreationForm):
    username = forms.CharField(max_length=30, label='User Name :')
    email = forms.EmailField(max_length=200, label='Email :')
    first_name = forms.CharField(max_length=100, help_text='First Name', label='First Name :')
    last_name = forms.CharField(max_length=100, help_text='Last Name', label='Last Name :')

    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'password1', 'password2',)

content/views.py
from django.http import HttpResponse
from django.shortcuts import render


# Create your views here.
def index(request):
    return HttpResponse("deneme")

product/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.contrib import messages
from django.http import HttpResponse, HttpResponseRedirect

from product.models import CommentFrom, Comment


# Create your views here.
def index(request):
    return render("Product page")


@login_required(login_url='/login')  # check login
def addcomment(request, id):
    url = request.META.get('HTTP_REFERER')
    if request.method == 'POST':
        form = CommentFrom(request.POST)
        if form.is_valid():
            current_user = request.user  # Access User session info
            data = Comment()
            data.user_id = current_user.id
            data.product_id = id
            data.subject = form.cleaned_data['subject']
            data.comment = form.cleaned_data['comment']
            data.rate = form.cleaned_data['rate']
            data.ip = request.META.get('REMOTE_ADDR')
            data.save()
            messages.success(request, "Yorumunuz başarı ile gönderilmiştir. Teşekkür Ederiz..")
            return HttpResponseRedirect('/')
        messages.warning("Yorumunuz Gönderilemedi. Lütfen kontrol ediniz..")
    return HttpResponseRedirect(url)

home/templates/aboutus.html
{% extends "homebase.html" %}

{% block title %}Hakkımızda {{ setting.company }}{% endblock %}
{% block keywords %}{{ setting.keywords }}{% endblock %}
{% block description %}{{ setting.description }}{% endblock %}

{% block head %}
    <link rel='shortcut icon' type='image/x-icon' href='{{ setting.icon.url }}'>
{% endblock %}



{% block content %}
    <div class="breadcrumbs">
		<div class="container">
			<ol class="breadcrumb breadcrumb1 animated wow slideInLeft" data-wow-delay=".5s">
				<li><a href="index.html"><span class="glyphicon glyphicon-home" aria-hidden="true"></span>Anasayfa</a></li>
				<li class="active">Hakkımızda</li>
			</ol>
		</div>
	</div>
	<!--//breadcrumbs-->
	<!--about-->
	<div class="about">
		<div class="container">
			<div class="title-info wow fadeInUp animated" data-wow-delay=".5s">
				<h3 class="title">Hakkımızda</h3>
			</div>
			<div class="about-info">
                {{ setting.aboutus | safe}}
            </div>
		</div>
	</div>
{% endblock %}

home/templates/contact.html
{% extends "homebase.html" %}

{% block title %}İletişim {{ setting.company }}{% endblock %}
{% block keywords %}{{ setting.keywords }}{% endblock %}
{% block description %}{{ setting.description }}{% endblock %}

{% block head %}
    <link rel='shortcut icon' type='image/x-icon' href='{{ setting.icon.url }}'>
{% endblock %}



{% block content %}
    <div class="breadcrumbs">
        <div class="container">
            <ol class="breadcrumb breadcrumb1 animated wow slideInLeft" data-wow-delay=".5s">
                <li><a href="index.html"><span class="glyphicon glyphicon-home" aria-hidden="true"></span>Anasayfa</a>
                </li>
                <li class="active">İletişim</li>
            </ol>
        </div>
    </div>
    <!--//breadcrumbs-->
    <!--contact-->
    <div class="contact">
        <div class="container">
            <div class="title-info wow fadeInUp animated" data-wow-delay=".5s">
                <h3 class="title">Iletisim </h3>
            </div>
            <iframe class="wow zoomIn animated animated" data-wow-delay=".5s"
                    src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d57537.641430789925!2d-74.03215321337959!3d40.719122105634035!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89c24fa5d33f083b%3A0xc80b8f06e177fe62!2sNew+York%2C+NY%2C+USA!5e0!3m2!1sen!2sin!4v1456152197129"
                    allowfullscreen=""></iframe>
        </div>
    </div>
    <!--address-->
    <div class="address">
        <div class="container">
            <div class="address-row">
                <div class="col-md-6 address-left wow fadeInLeft animated" data-wow-delay=".5s">
                    <div class="address-grid" style="height: 900px">
                        <p style="margin-top: 85px"></p>
                        <h4 class="wow fadeIndown animated" data-wow-delay=".5s">Bize Ulasın </h4>


                        {% if messages %}
                            {% for message in messages %}
                                <div class="alert alert- {{ message.tags }}" role="alert">
                                    {{ message }}
                                </div>
                            {% endfor %}
                        {% endif %}

                        <form action="" method="post">
                            {% csrf_token %}
                            {{ form.as_p }}

                            <input class="wow fadeIndown animated" data-wow-delay=".9s" type="submit" value="SEND">
                        </form>

                    </div>

                </div>
                <div class="col-md-6 address-right">
                    <div class="address-info wow fadeInRight animated" data-wow-delay=".5s">
                        <h4>ADDRESS</h4>
                        <p>{{ setting.address | safe }}</p>
                    </div>
                    <div class="address-info address-mdl wow fadeInRight animated" data-wow-delay=".7s">
                        <h4>PHONE </h4>
                        <p>{{ setting.phone | safe }}</p>
                    </div>
                    <div class="address-info wow fadeInRight animated" data-wow-delay=".6s">
                        <h4>MAIL</h4>
                        <p><a href="mailto:example@mail.com"> {{ setting.email | safe }}</a></p>
                    </div>
                    <div class="address-info address-mdl wow fadeInRight animated" data-wow-delay=".7s">

                        <p>{{ setting.contact | safe }}</p>
                    </div>
                </div>

            </div>
        </div>
    </div>
{% endblock %}

home/templates/content_detail.html
{% extends "homebase.html" %}

{% block title %}Kadromuz {{ setting.company }}{% endblock %}
{% block keywords %}{{ setting.keywords }}{% endblock %}
{% block description %}{{ setting.description }}{% endblock %}

{% block head %}
    <link rel='shortcut icon' type='image/x-icon' href='{{ setting.icon.url }}'>
{% endblock %}



{% block content %}
    <div class="breadcrumbs">
        <div class="container">
            <ol class="breadcrumb breadcrumb1 animated wow slideInLeft" data-wow-delay=".5s">
                <li><a href="index.html"><span class="glyphicon glyphicon-home" aria-hidden="true"></span>Anasayfa</a>
                </li>
                <li class="active">Kadromuz</li>
            </ol>
        </div>
    </div>
    <!--//breadcrumbs-->
    <!--about-->
    <div class="about">
        <div class="container">
            <img style="height: 300px;width: 350px; margin-left: 400px" src="{{ content.image.url }}">
            {{ content.detail|safe }}
            <hr>
            {% for rs in images %}
                <img src="{{ rs.image.url }}" height="200" alt="">
            {% endfor %}
        </div>
    </div>
{% endblock %}

home/templates/footer.html
<!--footer-->
<div class="footer">
    <div class="container">
        <div class="footer-info">
            <div class="col-md-4 footer-grids wow fadeInUp animated" data-wow-delay=".5s">
                <h4 class="footer-logo"><a href="index.html">Modern <b>Shoppe</b> <span class="tag">Everything for Kids world </span>
                </a></h4>
                <p>© 2016 Modern Shoppe . All rights reserved | Design by <a href="http://w3layouts.com"
                                                                             target="_blank">W3layouts</a></p>
            </div>
            <div class="col-md-4 footer-grids wow fadeInUp animated" data-wow-delay=".7s">
                <h3>Popular</h3>
                <ul>
                    <li><a href="about.html">About Us</a></li>
                    <li><a href="products.html">new</a></li>
                    <li><a href="contact.html">Contact Us</a></li>
                    <li><a href="faq.html">FAQ</a></li>
                    <li><a href="checkout.html">Wishlist</a></li>
                </ul>
            </div>
            <div class="col-md-4 footer-grids wow fadeInUp animated" data-wow-delay=".9s">
                <h3>Subscribe</h3>
                <p>Sign Up Now For More Information <br> About Our Company </p>
                <form>
                    <input type="text" placeholder="Enter Your Email" required="">
                    <input type="submit" value="Go">
                </form>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
</div>
{% load static %}
<!--//footer-->
<!--search jQuery-->
<script src="{% static 'js/main.js' %}"></script>
<!--//search jQuery-->
<!--smooth-scrolling-of-move-up-->
<script type="text/javascript">
    $(document).ready(function () {

        var defaults = {
            containerID: 'toTop', // fading element id
            containerHoverID: 'toTopHover', // fading element hover id
            scrollSpeed: 1200,
            easingType: 'linear'
        };

        $().UItoTop({easingType: 'easeOutQuart'});

    });
</script>
<!--//smooth-scrolling-of-move-up-->
<!--Bootstrap core JavaScript
================================================== -->
<!--Placed at the end of the document so the pages load faster -->
<script src="{% static 'js/bootstrap.js' %}"></script>

home/templates/homebase.html
<!DOCTYPE html>
<html>
<head>
    <title> {% block title %}Anasayfa{% endblock %}</title>
    <!-- for-mobile-apps -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="keywords" content="{% block keywords %}Anasayfa anahtar kelimeler {% endblock %}"/>
    <meta name="description" content="{% block description %}Anasayfa kısa  açıklama {% endblock %}"/>
    <script type="application/x-javascript"> addEventListener("load", function () {
        setTimeout(hideURLbar, 0);
    }, false);

    function hideURLbar() {
        window.scrollTo(0, 1);
    }
    </script>
    <!--//for-mobile-apps -->
    <!--Custom Theme files -->
    {% load static %}
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" type="text/css" media="all"/>
    <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css" media="all"/>
    <link rel="stylesheet" href="{% static 'css/flexslider.css' %}" type="text/css" media="screen"/>
    <!--//Custom Theme files -->
    <!--js-->
    <script src="{% static 'js/modernizr.custom.js' %}"></script>
    <!--//js-->
    <!--cart-->
    <script src="{% static 'js/simpleCart.min.js' %}"></script>
    <!--cart-->
    <!--web-fonts-->
    <link href='//fonts.googleapis.com/css?family=Raleway:400,100,100italic,200,200italic,300,400italic,500,500italic,600,600italic,700,700italic,800,800italic,900,900italic'
          rel='stylesheet' type='text/css'>
    <link href='//fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic'
          rel='stylesheet' type='text/css'>
    <link href='//fonts.googleapis.com/css?family=Pompiere' rel='stylesheet' type='text/css'>
    <link href='//fonts.googleapis.com/css?family=Fascinate' rel='stylesheet' type='text/css'>
    <!--web-fonts-->

    <!-- jQuery !-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <!-- jQuery UI !-->
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
    <!--animation-effect-->
    <link href="{% static 'css/animate.min.css' %}" rel="stylesheet">
    <script src="{% static 'cjs/wow.min.js' %}"></script>

    <script>
        new WOW().init();

    </script>
    <!--//animation-effect-->
    <!--start-smooth-scrolling-->
    <script type="text/javascript" src="{% static 'js/move-top.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/easing.js' %}"></script>
    <script type="text/javascript">
        jQuery(document).ready(function ($) {
            $(".scroll").click(function (event) {
                event.preventDefault();
                $('html,body').animate({scrollTop: $(this.hash).offset().top}, 1000);
            });
        });

    </script>
    <!--//end-smooth-scrolling-->
    {% block head %}{% endblock %}
</head>

<body>
{% include 'header.html' %}
{% block slider %}{% endblock %}
{% block content %}{% endblock %}
{% include 'footer.html' %}
{% block footer %}{% endblock %}
</body>
</html>

home/templates/product_comment.html
{% extends "homebase.html" %}

{% block title %}{{ setting.company }} Kullanıcı Mesajı{% endblock %}
{% block keywords %}{{ setting.keywords }}{% endblock %}
{% block description %}{{ setting.description }}{% endblock %}

{% block head %}
    <link rel='shortcut icon' type='image/x-icon' href='{{ setting.icon.url }}'>
{% endblock %}



{% block content %}
    <div class="breadcrumbs">
        <div class="container">
            <ol class="breadcrumb breadcrumb1 animated wow slideInLeft" data-wow-delay=".5s">
                <li><a href="/"><span class="glyphicon glyphicon-home" aria-hidden="true"></span>Anasayfa</a></li>
                <li><a href="#"><span class="glyphicon " aria-hidden="true"></span>Products</a></li>
                <li><a href="/category/{{ product.category_id }}/{{ product.category.slug }}"><span class="glyphicon "
                                                                                                    aria-hidden="true"></span>{{ product.category }}
                </a></li>
                <li><a href="/product/{{ product.id }}/{{ product.slug }}"><span class="glyphicon "
                                                                                 aria-hidden="true"></span>{{ product.title }}
                </a></li>
                <li class="active">Product Review</li>
            </ol>
        </div>
    </div>
    <!--//breadcrumbs-->
    <!--product_review-->
    <div class="address"><!--address-->
        <div class="container">
            <div class="address-row">
                <div class="col-md-6 address-left wow fadeInLeft animated" style="margin-left:300px;"
                     data-wow-delay=".5s">

                    <div class="address-grid">
                        <h4 class="wow fadeIndown animated" data-wow-delay=".5s">Sen de bu ürün hakkındaki fikirlerini
                            paylas!</h4>
                        {% if messages %}
                            {% for message in messages %}
                                <div class="alert alert-warning-{{ message.tags }}" role="alert">
                                    {{ message }}
                                </div>

                            {% endfor %}
                        {% endif %}
                        <form action="/product/addcomment/{{ product.id }}" method="post">
                            {% csrf_token %}

                            <input class="wow fadeIndown animated" data-wow-delay=".7s" type="text" name="subject"
                                   id="id_subject"
                                   placeholder="Mesaj Konusu"
                                   required="">
                            <textarea class="wow fadeIndown animated" data-wow-delay=".8s" name="comment"
                                      id="id_comment"
                                      placeholder="Kullanıcı Mesajı"
                                      required=""></textarea>
                            <div class="single-rating">
                                <b style="color: #f0f0f0; margin-left: 5px">Yıldız veriniz:</b>
                                <span class="starRating">

                                    <input id="rating5" type="radio" name="rate" value="5" >
                                    <label for="rating5">5</label>
                                    <input id="rating4" type="radio" name="rate" value="4">
                                    <label for="rating4">4</label>
                                    <input id="rating3" type="radio" name="rate" value="3">
                                    <label for="rating3">3</label>
                                    <input id="rating2" type="radio" name="rate" value="2">
                                    <label for="rating2">2</label>
                                    <input id="rating1" type="radio" name="rate" value="1">
                                    <label for="rating1">1</label>
                                </span>
                            </div>

                            {% if user.id is not None %}
                                <input class="wow fadeIndown animated" data-wow-delay=".9s" type="submit" value="SEND">
                            {% else %}
                                Yorum eklemek için <a href="/login">login</a>  olunuz!
                            {% endif %}


                        </form>
                    </div>

                </div>

            </div>
        </div>
    </div>
    <!--//contact-->

{% endblock %}